### ISSUE TITLE
Notify user with a message " waiting for other player " while its the opponent's move(Medium)

### ISSUE THREAD

**Issue by bahashmi** [Stevenc0211/cs414-f17-301-Polymorphs#107]
need a textView.xml file

**Comment by thenotoriousrog** [comment]
There's a couple ways to do this. The first is to use a textview like Badr was saying. Which simply tells the user who's turn it is. Another idea (which is the idea I prefer) is to highlight the castle wall of the player of depending on who's turn it is. I think it is a very intuitive way to do this and on top of that it does not take up any extra space on the app which is pretty crucial.

**Comment by thenotoriousrog** [comment]
Finished thanks to miles and I
